server:
  port: 8080

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: create-drop